# This sorts the list in alphabetical order and generates other list files

name: Sort site list

# Controls when the workflow will run
on:
  push

jobs:
  # Encoding job
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install dependencies
      - name: Update sorting
        run: |
          echo "This will eventually do something"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated sorting" || echo "No changes to commit"
          git push
