# This sorts the list in alphabetical order and generates other list files

name: Sort site list

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  # Encoding job
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install dependencies
      - uses: dart-lang/setup-dart@v1.3
      # Sort the list
      - name: Update sorting
        run: |
          dart bin/sort.dart
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated sorting" || echo "No changes to commit"
          git push
